version: "3"
networks:
  dockerlan:
    name: dockerlan
    external: true
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      # DISK_SIZE: "8G" # so no data disk is created as a file
      DEBUG: Y
      # DHCP: Y
    devices:
      - /dev/kvm
      - /dev/vhost-net
    networks:
     - dockerlan
    device_cgroup_rules:
      - 'c *:* rwm'      
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/compose_services/vdsm/system_storage:/storage
      # TODO: passthrough a storage device for data
    restart: on-failure
    stop_grace_period: 2m
