version: "3"
networks:
  dockerlan:
    name: dockerlan
    external: true
services:
  dsm:
    container_name: dsm
    image: vdsm/virtual-dsm
    environment:
      DISK_SIZE: "8G"
      DEBUG: Y
      # DHCP: Y
    devices:
      - /dev/kvm
      - /dev/vhost-net
    networks:
     - dockerlan
    device_cgroup_rules:
      - 'c *:* rwm'      
    cap_add:
      - NET_ADMIN
    ports:
      - 10010:5000
    volumes:
      - /opt/compose_services/vdsm/system_storage:/storage
    restart: on-failure
    stop_grace_period: 2m
