#!/bin/sh /etc/rc.common

START=90
NAME=tethermond
USE_PROCD=1
PROG=/root/.bin/tether-router-monitor
export PATH=/root/.bin:/usr/sbin:/usr/bin:/sbin:/bin
start_service() {
	procd_open_instance $NAME
	procd_set_param command "$PROG"
	
	# Set environment variables
	
	procd_set_param env PATH=$PATH PUSH_INTERVAL_SECONDS="10" PUSH_URL="https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push" PUSH_USERNAME="" PUSH_PASSWORD=""
	procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param user root
        procd_set_param pidfile /var/run/tethermond.pid
	procd_close_instance
}

stop_service() {
	procd_send_signal tethermond
}

